# Generated by Django 5.2.17 on 2026-08-11 20:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('unmatched', 'Unmatch'), ('scheduled', 'Planifié'), ('ended', 'Terminé')], default='active', max_length=20)),
                ('user_1_message_count', models.PositiveIntegerField(default=0)),
                ('user_2_message_count', models.PositiveIntegerField(default=0)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('meet_link', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=40, null=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Homme'), ('female', 'Femme')], max_length=10)),
                ('city', models.CharField(max_length=120)),
                ('country', models.CharField(default='Sénégal', max_length=120)),
                ('residence_country', models.CharField(blank=True, max_length=120, null=True)),
                ('religion', models.CharField(blank=True, choices=[('musulmane', 'Musulmane'), ('chretienne', 'Chrétienne'), ('autre', 'Autre')], max_length=20, null=True)),
                ('profession', models.CharField(blank=True, max_length=180, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('looking_for', models.TextField(blank=True, null=True)),
                ('photo_url', models.TextField(blank=True, null=True)),
                ('photo_url_2', models.TextField(blank=True, null=True)),
                ('photo_url_3', models.TextField(blank=True, null=True)),
                ('registration_status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='approved', max_length=20)),
                ('role', models.CharField(choices=[('member', 'Membre'), ('admin', 'Admin')], default='member', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('subscription_tier', models.CharField(choices=[('free', 'Gratuit'), ('premium_10d', 'Premium 10 jours'), ('premium_1m', 'Premium 1 mois'), ('premium_2m', 'Premium 2 mois'), ('vip_1m', 'VIP 1 mois'), ('vip_2m', 'VIP 2 mois'), ('vip_femme_1w', 'VIP Femme 1 semaine')], default='free', max_length=30)),
                ('subscription_status', models.CharField(choices=[('inactive', 'Inactif'), ('active', 'Actif'), ('expired', 'Expiré')], default='inactive', max_length=20)),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True)),
                ('likes_received_count', models.PositiveIntegerField(default=0)),
                ('likes_given_count', models.PositiveIntegerField(default=0)),
                ('matches_count', models.PositiveIntegerField(default=0)),
                ('is_boosted', models.BooleanField(default=False)),
                ('boost_end_date', models.DateTimeField(blank=True, null=True)),
                ('last_active_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('last_seen_visibility', models.CharField(choices=[('everyone', 'Tout le monde'), ('matches', 'Matchs uniquement'), ('nobody', 'Personne')], default='everyone', max_length=20)),
                ('hide_age', models.BooleanField(default=False)),
                ('notification_preferences', models.JSONField(default=dict)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('banned_at', models.DateTimeField(blank=True, null=True)),
                ('ban_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('new_like', 'Nouveau like'), ('new_match', 'Nouveau match'), ('new_message', 'Nouveau message'), ('subscription_activated', 'Abonnement activé'), ('subscription_expired', 'Abonnement expiré'), ('profile_approved', 'Profil approuvé'), ('profile_rejected', 'Profil rejeté'), ('new_registration', 'Nouvelle inscription'), ('boost_activated', 'Boost activé')], max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.match')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_notifications', to='core.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, default='')),
                ('message_type', models.CharField(choices=[('text', 'Texte'), ('voice', 'Vocal'), ('system', 'Système')], default='text', max_length=20)),
                ('voice_url', models.TextField(blank=True, null=True)),
                ('voice_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('original_content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.match')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to='core.profile')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='user_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user1', to='core.profile'),
        ),
        migrations.AddField(
            model_name='match',
            name='user_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user2', to='core.profile'),
        ),
        migrations.CreateModel(
            name='ConversationHide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_by', to='core.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_conversations', to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='CoachingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=40)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Homme'), ('female', 'Femme')], max_length=10, null=True)),
                ('situation', models.TextField(blank=True, null=True)),
                ('requested_date', models.DateField()),
                ('time_slot', models.CharField(choices=[('matin', 'Matin'), ('aprem', 'Après-midi'), ('soir', 'Soir')], max_length=20)),
                ('theme', models.CharField(choices=[('couple', 'Couple'), ('rupture', 'Rupture'), ('confiance', 'Confiance'), ('communication', 'Communication'), ('rencontres', 'Rencontres'), ('mariage', 'Mariage'), ('autre', 'Autre')], max_length=30)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('confirmed_date', models.DateTimeField(blank=True, null=True)),
                ('meet_link', models.TextField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20)),
                ('payment_amount', models.PositiveIntegerField(default=26000)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaching_requests', to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_received', to='core.profile')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_made', to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='BannedIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_normalized', models.TextField(blank=True, null=True)),
                ('phone_normalized', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('banned_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banned_identities', to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileGalleryPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField()),
                ('photo_url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photos', to='core.profile')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('fake_profile', 'Faux profil'), ('harassment', 'Harcèlement'), ('inappropriate_content', 'Contenu inapproprié'), ('scam', 'Arnaque'), ('spam', 'Spam'), ('other', 'Autre'), ('platform', 'Plateforme')], max_length=40)),
                ('message', models.TextField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('report_kind', models.CharField(choices=[('profile', 'Profil'), ('support', 'Support')], default='profile', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('resolved', 'Résolu'), ('dismissed', 'Rejeté'), ('reviewed', 'Examiné'), ('action_taken', 'Action prise')], default='pending', max_length=20)),
                ('resolution', models.CharField(blank=True, max_length=40, null=True)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_received', to='core.profile')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to='core.profile')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_resolved', to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier', models.CharField(choices=[('free', 'Gratuit'), ('premium_10d', 'Premium 10 jours'), ('premium_1m', 'Premium 1 mois'), ('premium_2m', 'Premium 2 mois'), ('vip_1m', 'VIP 1 mois'), ('vip_2m', 'VIP 2 mois'), ('vip_femme_1w', 'VIP Femme 1 semaine')], max_length=30)),
                ('status', models.CharField(choices=[('inactive', 'Inactif'), ('active', 'Actif'), ('expired', 'Expiré')], default='inactive', max_length=20)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('plan_tier', models.CharField(blank=True, choices=[('free', 'Gratuit'), ('premium_10d', 'Premium 10 jours'), ('premium_1m', 'Premium 1 mois'), ('premium_2m', 'Premium 2 mois'), ('vip_1m', 'VIP 1 mois'), ('vip_2m', 'VIP 2 mois'), ('vip_femme_1w', 'VIP Femme 1 semaine')], max_length=30, null=True)),
                ('order_id', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Swipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_like', models.BooleanField(default=False)),
                ('is_super_like', models.BooleanField(default=False)),
                ('action', models.CharField(choices=[('pass', 'Pass'), ('like', 'Like'), ('super_like', 'Super like')], default='pass', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('swiped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes_received', to='core.profile')),
                ('swiper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes_made', to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=120)),
                ('author_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('content', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='core.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=120, unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('payment_method', models.CharField(blank=True, choices=[('wave', 'Wave'), ('orange_money', 'Orange Money'), ('cb', 'Carte bancaire')], max_length=30, null=True)),
                ('type', models.CharField(choices=[('subscription', 'Abonnement'), ('coaching', 'Coaching'), ('boost', 'Boost')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20)),
                ('naboo_transaction_id', models.CharField(blank=True, max_length=120, null=True)),
                ('payment_details', models.JSONField(blank=True, default=dict)),
                ('plan_tier', models.CharField(blank=True, choices=[('free', 'Gratuit'), ('premium_10d', 'Premium 10 jours'), ('premium_1m', 'Premium 1 mois'), ('premium_2m', 'Premium 2 mois'), ('vip_1m', 'VIP 1 mois'), ('vip_2m', 'VIP 2 mois'), ('vip_femme_1w', 'VIP Femme 1 semaine')], max_length=30, null=True)),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coaching_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.coachingrequest')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.subscription')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_subscriptions', to='core.transaction'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['gender'], name='core_profil_gender_2b6106_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['city'], name='core_profil_city_346226_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['registration_status'], name='core_profil_registr_883d20_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['-created_at'], name='core_profil_created_ed0ca7_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['-last_active_at'], name='core_profil_last_ac_7ce2e5_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='core_notifi_user_id_1cc5b6_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['match', 'created_at'], name='core_messag_match_i_f4a1d0_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender'], name='core_messag_sender__064541_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['user_1'], name='core_match_user_1__ac4018_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['user_2'], name='core_match_user_2__f261dd_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status'], name='core_match_status_b71399_idx'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('user_1', 'user_2'), name='unique_match_pair'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('user_1', models.F('user_2')), _negated=True), name='no_self_match'),
        ),
        migrations.AddConstraint(
            model_name='conversationhide',
            constraint=models.UniqueConstraint(fields=('user', 'partner'), name='unique_conversation_hide'),
        ),
        migrations.AddConstraint(
            model_name='conversationhide',
            constraint=models.CheckConstraint(condition=models.Q(('user', models.F('partner')), _negated=True), name='no_self_hide'),
        ),
        migrations.AddConstraint(
            model_name='blockeduser',
            constraint=models.UniqueConstraint(fields=('blocker', 'blocked'), name='unique_block'),
        ),
        migrations.AddConstraint(
            model_name='blockeduser',
            constraint=models.CheckConstraint(condition=models.Q(('blocker', models.F('blocked')), _negated=True), name='no_self_block'),
        ),
        migrations.AddConstraint(
            model_name='bannedidentity',
            constraint=models.CheckConstraint(condition=models.Q(('email_normalized__isnull', False), ('phone_normalized__isnull', False), _connector='OR'), name='banned_has_identifier'),
        ),
        migrations.AddConstraint(
            model_name='profilegalleryphoto',
            constraint=models.UniqueConstraint(fields=('profile', 'position'), name='unique_gallery_position'),
        ),
        migrations.AddConstraint(
            model_name='profilegalleryphoto',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1), ('position__lte', 3)), name='gallery_position_1_3'),
        ),
        migrations.AddIndex(
            model_name='swipe',
            index=models.Index(fields=['swiper', 'swiped'], name='core_swipe_swiper__dbd8d7_idx'),
        ),
        migrations.AddIndex(
            model_name='swipe',
            index=models.Index(fields=['-created_at'], name='core_swipe_created_421590_idx'),
        ),
        migrations.AddConstraint(
            model_name='swipe',
            constraint=models.UniqueConstraint(fields=('swiper', 'swiped'), name='unique_swipe_pair'),
        ),
    ]
