# Generated by Django 5.2.17 on 2026-08-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_own_profile_gallery_filters"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="apple_uid",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
