# Generated by Django 5.2.17 on 2026-08-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_profile_likes_inbox_seen_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Texte'), ('voice', 'Vocal'), ('image', 'Image'), ('system', 'Système')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='relationship_intent',
            field=models.CharField(blank=True, choices=[('mariage', 'Mariage'), ('relation_serieuse', 'Relation sérieuse'), ('a_preciser', 'À préciser')], default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscription_tier',
            field=models.CharField(choices=[('free', 'Gratuit'), ('journee_amoureuse', 'Journée amoureuse'), ('pass_amour', 'Pass Amour'), ('eternite', 'Éternité'), ('vip_1m', 'VIP'), ('pass_femme', 'Pass Femme'), ('premium_10d', 'Premium 10 jours'), ('premium_1m', 'Premium 1 mois'), ('premium_2m', 'Premium 2 mois'), ('vip_2m', 'VIP 2 mois'), ('vip_femme_1w', 'VIP Femme 1 semaine')], default='free', max_length=30),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan_tier',
            field=models.CharField(blank=True, choices=[('free', 'Gratuit'), ('journee_amoureuse', 'Journée amoureuse'), ('pass_amour', 'Pass Amour'), ('eternite', 'Éternité'), ('vip_1m', 'VIP'), ('pass_femme', 'Pass Femme'), ('premium_10d', 'Premium 10 jours'), ('premium_1m', 'Premium 1 mois'), ('premium_2m', 'Premium 2 mois'), ('vip_2m', 'VIP 2 mois'), ('vip_femme_1w', 'VIP Femme 1 semaine')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='tier',
            field=models.CharField(choices=[('free', 'Gratuit'), ('journee_amoureuse', 'Journée amoureuse'), ('pass_amour', 'Pass Amour'), ('eternite', 'Éternité'), ('vip_1m', 'VIP'), ('pass_femme', 'Pass Femme'), ('premium_10d', 'Premium 10 jours'), ('premium_1m', 'Premium 1 mois'), ('premium_2m', 'Premium 2 mois'), ('vip_2m', 'VIP 2 mois'), ('vip_femme_1w', 'VIP Femme 1 semaine')], max_length=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='plan_tier',
            field=models.CharField(blank=True, choices=[('free', 'Gratuit'), ('journee_amoureuse', 'Journée amoureuse'), ('pass_amour', 'Pass Amour'), ('eternite', 'Éternité'), ('vip_1m', 'VIP'), ('pass_femme', 'Pass Femme'), ('premium_10d', 'Premium 10 jours'), ('premium_1m', 'Premium 1 mois'), ('premium_2m', 'Premium 2 mois'), ('vip_2m', 'VIP 2 mois'), ('vip_femme_1w', 'VIP Femme 1 semaine')], max_length=30, null=True),
        ),
    ]
