# Generated by Django 5.2.17 on 2026-09-07 12:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_promocode_plan_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('critical', 'Critique'), ('error', 'Erreur'), ('warning', 'Avertissement'), ('info', 'Info')], db_index=True, default='error', max_length=16)),
                ('source', models.CharField(choices=[('http', 'HTTP'), ('exception', 'Exception'), ('slow', 'Requête lente'), ('logging', 'Logger'), ('celery', 'Celery'), ('payment', 'Paiement'), ('email', 'Email'), ('push', 'Push'), ('system', 'Système')], db_index=True, default='system', max_length=24)),
                ('title', models.CharField(max_length=220)),
                ('message', models.TextField(blank=True, default='')),
                ('path', models.CharField(blank=True, default='', max_length=500)),
                ('method', models.CharField(blank=True, default='', max_length=12)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('exception_type', models.CharField(blank=True, default='', max_length=120)),
                ('location', models.CharField(blank=True, default='', help_text='fichier:ligne', max_length=300)),
                ('traceback', models.TextField(blank=True, default='')),
                ('fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('user_email', models.CharField(blank=True, default='', max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_created_1a76fa_idx',
            old_name='core_auditl_created_6a0b0d_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_action_d80c2d_idx',
            old_name='core_auditl_action_8e1f2a_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_actor_i_502baf_idx',
            old_name='core_auditl_actor_i_5c3d1e_idx',
        ),
        migrations.RenameIndex(
            model_name='campaigndelivery',
            new_name='core_campai_profile_4bffed_idx',
            old_name='core_campa_profile_8a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='campaigndelivery',
            new_name='core_campai_campaig_5420ec_idx',
            old_name='core_campa_campaig_3d4e5f_idx',
        ),
        migrations.AlterField(
            model_name='coachingrequest',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('failed', 'Échoué'), ('refunded', 'Remboursé'), ('dispute', 'Litige / Chargeback')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_like', 'Nouveau like'), ('new_match', 'Nouveau match'), ('new_message', 'Nouveau message'), ('subscription_activated', 'Abonnement activé'), ('subscription_expired', 'Abonnement expiré'), ('profile_approved', 'Profil approuvé'), ('profile_rejected', 'Profil rejeté'), ('new_registration', 'Nouvelle inscription'), ('boost_activated', 'Boost activé'), ('moderation_warning', 'Avertissement modération')], max_length=40),
        ),
        migrations.AddIndex(
            model_name='systemevent',
            index=models.Index(fields=['-last_seen_at', 'level'], name='core_system_last_se_a7942f_idx'),
        ),
        migrations.AddIndex(
            model_name='systemevent',
            index=models.Index(fields=['fingerprint', '-last_seen_at'], name='core_system_fingerp_4b71c9_idx'),
        ),
        migrations.AddIndex(
            model_name='systemevent',
            index=models.Index(fields=['source', '-last_seen_at'], name='core_system_source_3d883a_idx'),
        ),
    ]
