from django.urls import path

from . import views

app_name = "api"

urlpatterns = [
    path("health/", views.health, name="health"),
    path("site-config/", views.site_config, name="site_config"),
    path("discover/feed/", views.discover_feed, name="discover_feed"),
    path("swipes/", views.swipes, name="swipes"),
    path("likes/incoming/", views.likes_incoming, name="likes_incoming"),
    path("likes/count/", views.likes_count, name="likes_count"),
    path("matches/", views.matches, name="matches"),
    path("matches/<uuid:partner_id>/unmatch/", views.unmatch, name="unmatch"),
    path("messages/", views.messages, name="messages"),
    path("messages/<uuid:message_id>/", views.message_delete, name="message_delete"),
    path("messages/open/", views.messages_open, name="messages_open"),
    path("messages/unread-count/", views.unread_messages, name="unread_messages"),
    path("messages/inbox/", views.messages_inbox, name="messages_inbox"),
    path("messages/read-receipts/", views.message_read_receipts, name="message_read_receipts"),
    path("messages/mark-read/", views.message_mark_read, name="message_mark_read"),
    path("compatibility/<uuid:profile_id>/", views.compatibility_score_api, name="compatibility_score"),
    path("notifications/", views.notifications, name="notifications"),
    path("notifications/unread-count/", views.unread_notifications_count, name="unread_notifications_count"),
    path("notifications/mark-read/", views.notifications_mark_read, name="notifications_mark_read"),
    path("payments/checkout/", views.payments_checkout, name="payments_checkout"),
    path("payments/confirm/", views.payments_confirm, name="payments_confirm"),
    path("payments/cinetpay/notify/", views.cinetpay_notify, name="cinetpay_notify"),
    path("payments/naboo-webhook/", views.cinetpay_notify, name="naboo_webhook"),
    path("reports/", views.reports, name="reports"),
    path("conversations/hide/", views.conversation_hide, name="conversation_hide"),
    path("conversations/<uuid:partner_id>/accept/", views.conversation_accept, name="conversation_accept"),
    path("conversations/<uuid:partner_id>/decline/", views.conversation_decline, name="conversation_decline"),
    path("blocked-users/", views.blocked_users, name="blocked_users"),
    path("coaching/checkout/", views.coaching_checkout, name="coaching_checkout"),
    path("push/config/", views.push_config, name="push_config"),
    path("push/status/", views.push_status, name="push_status"),
    path("push/test/", views.push_test, name="push_test"),
    path("push/register/", views.push_register, name="push_register"),
    path("push/unregister/", views.push_unregister, name="push_unregister"),
    path("auth/google/", views.auth_google, name="auth_google"),
    path("auth/apple/", views.auth_apple, name="auth_apple"),
    path("auth/signup/check/", views.signup_check, name="signup_check"),
    path("auth/signup/complete/", views.signup_complete, name="signup_complete"),
    path("auth/signup/location/", views.signup_location, name="signup_location"),
    path("onboarding/step/", views.onboarding_step, name="onboarding_step"),
    path("onboarding/photo/", views.onboarding_photo, name="onboarding_photo"),
    path("profile/update/", views.profile_update, name="profile_update"),
    path("profile/email/", views.profile_email, name="profile_email"),
    path("profile/password/", views.profile_password, name="profile_password"),
    path("profile/photo/", views.profile_photo, name="profile_photo"),
    path("profile/photo/delete/", views.profile_photo_delete, name="profile_photo_delete"),
    path("profile/photo/primary/", views.profile_photo_primary, name="profile_photo_primary"),
    path("profile/filters/", views.profile_filters, name="profile_filters"),
    path("profile/delete/", views.profile_delete, name="profile_delete"),
]
